version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-gems:
        patterns:
          - "*"
        exclude-patterns:
          - "rails"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
